name: CI/CD Pipeline

on:
  release:
    types: [published]
    
jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create folder & copy files
        run: |
          name=$(basename ${{ github.ref }})
          echo $name
          mkdir $name
          cp -r en $name
          cp -r ru $name
          cp -r index.html $name
          mkdir site
          cp -r $name site
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          keep_files: true
